name: Cypress tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Regression Tricentis
        uses: cypress-io/github-action@v2
        with:
          spec: cypress/e2e/login.cy.js
          browser: Chrome
